config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('triton-admin/', include('shop.urls')),
]

shop/urls.py
from django.urls import path

from shop import views
from shop.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDetailView, ProductDeleteView

app_name = 'shop'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/products', ProductListView.as_view(), name='admin-products'),
    path('dashboard/products/create', ProductCreateView.as_view(), name='admin-products-create'),
    path('dashboard/products/edit/<int:pk>', ProductUpdateView.as_view(), name='admin-products-update'),
    path('dashboard/products/detail/<int:pk>', ProductDetailView.as_view(), name='admin-products-detail'),
    path('dashboard/products/delete/<int:pk>', ProductDeleteView.as_view(), name='admin-products-delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import AuthView, RegisterView

app_name = 'users'

urlpatterns = [
    path('login/', AuthView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
]

shop/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='описание категории')
    image = models.ImageField(verbose_name='картинка категории', upload_to='images/category/%Y/%m/%d')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='название продукта')
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.PROTECT)
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='описание товара')
    price = models.FloatField(verbose_name='цена товара')
    image = models.ImageField(verbose_name='картинка товара', upload_to='images/product/%Y/%m/%d')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

shop/forms.py
from django import forms

from shop.models import Product


class StyleFormMixin(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import User


class StyleFormMixin(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class AuthForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ['email', 'password']

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop.forms import ProductForm
from shop.models import Product


# Create your views here.
def dashboard(request):
    context = {

    }
    return render(request, 'shop/admin_dashboard.html', context)


class ProductListView(ListView):
    model = Product
    extra_context = {
        'products_count': Product.objects.count()
    }
    paginate_by = 10


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm


class ProductDeleteView(DeleteView):
    model = Product

users/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import RegisterForm, AuthForm


# Create your views here.
class RegisterView(CreateView):
    form_class = RegisterForm
    reverse_url = reverse_lazy('users:login')


class AuthView(LoginView):
    form_class = AuthForm

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/321919f306.js" crossorigin="anonymous"></script>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
{% block content %}

{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/includes/admin_offcanvas.html
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample"
     aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Triton | Панель управления</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:dashboard' %}"><i class="fa-solid fa-house"></i> Главная</a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:admin-products' %}"><i class="fa-solid fa-basket-shopping"></i>
                    Товары</a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa-solid fa-list"></i> Категории</a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#"><i class="fa-solid fa-handshake-simple"></i>
                    Партнеры</a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#"><i class="fa-regular fa-money-bill-1"></i>
                    Акции</a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#"><i class="fa-solid fa-gears"></i> Настройки
                </a>
            </li>
            <hr>
            <li class="nav-item">
                <a class="nav-link text-danger" aria-current="page" href="#"><i
                        class="fa-solid fa-right-from-bracket"></i> Выход
                </a>
            </li>
        </ul>
    </div>
</div>

templates/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"
                   aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/shop/admin_dashboard.html
{% extends 'base.html' %}

{% block title %}
    Triton | Администрирование
{% endblock %}

{% block content %}
    <div class="container">
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
                aria-controls="offcanvasExample">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="row">
            <h1 class="mb-4 mt-4">Панель управления <i class="fa-solid fa-user-tie"></i></h1>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Акции</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Категории</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Подкатегории</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h1 class="mb-4 mt-4">Метрики <i class="fa-solid fa-chart-simple"></i></h1>
            <div class="col-12 col-sm-6 col-lg-6 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Посещаемость</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-6 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Популярные товары</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-12 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Отказы</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h1 class="mb-4 mt-4">Общая статистика <i class="fa-solid fa-stethoscope"></i></h1>
            <div class="col-12 col-sm-6 col-lg-6 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h2>Уникальных клиентов</h2>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-6 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h2>Уникальный товаров</h2>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-12 mb-4">
                <div class="card card__stat">
                    <div class="card-body text-center">
                        <h1>Категорий</h1>
                    </div>
                </div>
            </div>
        </div>

        {% include 'includes/admin_offcanvas.html' %}

    </div>
{% endblock %}

templates/shop/product_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Triton | Подтверждения удаления
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-4 justify-content-center">
            <div class="col-12 col-lg-6">
                <form method="post">
                    <div class="card">
                        <div class="card-header text-center">
                            <h1>Удаление товара</h1>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <p>Вы действительно хотите
                                удалить товар - {{ product.name }}, из базы?</p>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-danger w-100" type="submit">Удалить</button>
                            <a href="{% url 'shop:admin-products' %}" class="btn btn-primary w-100 mt-2">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}

{% block title %}
    Triton | {{ product.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-4 justify-content-center">
            <div class="col-12 col-lg-8">
                <div class="card">
                    <div class="card-header text-center">
                        <h1>{{ product.name }}</h1>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 text-center mb-4">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}"
                                         class="img-fluid rounded" style="max-height: 300px;">
                                {% else %}
                                    <div class="bg-light rounded d-flex align-items-center justify-content-center"
                                         style="height: 300px;">
                                        <span class="text-muted">Изображение отсутствует</span>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <p><strong>Категория:</strong> {{ product.category }}</p>
                                <p><strong>Цена:</strong> {{ product.price }} руб.</p>
                                <p><strong>URL:</strong> {{ product.slug }}</p>
                                <hr>
                                <h5>Описание:</h5>
                                <p>{{ product.description }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'shop:admin-products' %}" class="btn btn-primary">
                                <i class="fa-solid fa-arrow-left"></i> Вернуться к списку
                            </a>
                            <div>
                                <a href="{% url 'shop:admin-products-update' product.pk %}" class="btn btn-warning">
                                    <i class="fa-solid fa-pencil"></i> Редактировать
                                </a>
                                <a href="{% url 'shop:admin-products-delete' product.pk %}" class="btn btn-danger ms-2">
                                    <i class="fa-solid fa-trash-can"></i> Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product_form.html
{% extends 'base.html' %}

{% block title %}
    Triton |
    {% if client %}
        Редактирование товара
    {% else %}
        Добавление товара
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
                aria-controls="offcanvasExample">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="row mt-4 justify-content-center">
            <div class="col-12 col-lg-6">
                <form method="post">
                    <div class="card">
                        <div class="card-header text-center">
                            {% if client %}
                                <h1>Редактирование товара</h1>
                            {% else %}
                                <h1>Добавление товара</h1>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer">
                            {% if client %}
                                <button class="btn btn-primary w-100" type="submit">Сохранить изменения</button>
                            {% else %}
                                <button class="btn btn-primary w-100" type="submit">Добавить товар</button>
                            {% endif %}
                            <a href="{% url 'shop:admin-products' %}" class="btn btn-danger w-100 mt-2">Вернуться</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product_list.html
{% extends 'base.html' %}

{% block title %}
    Triton | Администрирование
{% endblock %}

{% block content %}
    <div class="container">
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
                aria-controls="offcanvasExample">
            <i class="fa-solid fa-bars"></i>
        </button>

        <div class="row mt-4">
            <h1>Продукты</h1>
            <div class="col mt-2">
                <a href="{% url 'shop:admin-products-create' %}" class="btn btn-primary col-12 col-sm-5 col-lg-3 col-xl-2 mb-2">Добавить
                    <i
                            class="fa-solid fa-plus"></i></a>
                <a href="#" class="btn btn-primary col-12 col-sm-5 col-lg-3 col-xl-2 mb-2">Загрузить из Excel <i
                        class="fa-solid fa-table"></i></a>

            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="col-1">ID</th>
                            <th class="col-2">Название</th>
                            <th class="col-2">Категория</th>
                            <th class="col-1">Цена</th>
                            <th class="col-2">URL</th>
                            <th class="col-2">Описание</th>
                            <th class="col-2">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.name }}</td>
                                <td>{{ object.category }}</td>
                                <td>{{ object.price }}</td>
                                <td>{{ object.slug }}</td>
                                <td>{{ object.description|truncatechars:50 }}</td>
                                <td>
                                    <a href="{% url 'shop:admin-products-detail' object.pk %}"
                                       class="btn btn-primary mb-1">
                                        <i class="fa-solid fa-eye"></i>
                                    </a>
                                    <a href="{% url 'shop:admin-products-update' object.pk %}"
                                       class="btn btn-primary mb-1">
                                        <i class="fa-solid fa-pencil"></i>
                                    </a>
                                    <a href="{% url 'shop:admin-products-delete' object.pk %}"
                                       class="btn btn-danger mb-1">
                                        <i class="fa-solid fa-trash-can"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
        <div class="row">
            <div class="col">
                {% include 'includes/pagination.html' %}
            </div>
            <div class="col text-end">
                <p>Всего : {{ products_count }}</p>
            </div>


        </div>

        {% include 'includes/admin_offcanvas.html' %}

    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Triton | Авторизация
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-lg-6">
                <form method="post">
                    <div class="card mt-4">
                        <div class="card-header text-center">
                            <h1>Авторизация</h1>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary w-100">Войти</button>
                            <a href="{% url 'users:register' %}" class="nav nav-link">Впервые здесь? Зарегистрируйтесь</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    Triton | Регистрация
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-lg-6">
                <form method="post">
                    <div class="card mt-4">
                        <div class="card-header text-center">
                            <h1>Регистрация</h1>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button class="btn btn-primary w-100">Зарегистрироваться</button>
                            <a href="{% url 'users:login' %}" class="nav nav-link">Уже есть аккаунт? Войти</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}